name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Asegúrate de que esto coincida con el nombre de tu rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Install and Build
      run: |
        npm install
        npm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages  # La rama en la que se desplegará tu sitio
        folder: dist       # El directorio que Vite construye a, suele ser `dist`
